### ISSUE TITLE
RethinkDB is shutting down, what database to use now?

### ISSUE THREAD

**Issue by CHEWTOYS** [yamalight/building-products-with-js#12]
RethinkDB is shutting down, what database to use now?
https://rethinkdb.com/blog/rethinkdb-shutdown/

I think you should update the server with new database :P

**Comment by yamalight** [comment]
@CHEWTOYS I don't think it requires immediate action - current version of rethinkdb is pretty stable and gives all the features we currently need.
I also hope Stripe will dedicate at least some resources to support open source version of rethinkdb in the future.

I might do additional video on switching DBs at some point though :)

**Comment by kaoussi** [comment]
the company behind RethinkDB is shutting down, both Horizon and RethinkDB are still there and may find a new home!
