### ISSUE TITLE
Persistent login/register errors in Redux.

### ISSUE THREAD

**Issue by surtich** [yamalight/building-products-with-js#15]
I found a subtle error in the client application:
* Go to `/login`.
* Enter an incorrect username / password.
* An error is displayed.
* Navigate to `/register`: The error persists with different text.

The same happens when you navigate from `/register` to` /login` with an error.

I think it would be good to create a component to handle errors and that errors will be displayed on the homepage with a disposable alert.

**Comment by EliasJorgensen** [comment]
Ah, yeah i've also noticed this issue in a personal project, where i implemented error handling basically the same way, as in this project.

It would also be a possibility to just create 2 separate entries in the global state for the error handling, one for login and one for register. I think that would also enforce a better separation of concern.

**Comment by yamalight** [comment]
Valid points. Having separate errors would indeed help that.
Would be happy to accept a PR with this change 👍
