### ISSUE TITLE
Problem with dev dependecies

### ISSUE THREAD

**Issue by VoLuong** [yamalight/building-products-with-js#6]
```
npm WARN eslint-config-airbnb@9.0.1 requires a peer of eslint@^2.9.0 but none was installed.
npm WARN eslint-config-airbnb@9.0.1 requires a peer of eslint-plugin-jsx-a11y@^1.2.0 but none was installed.
npm WARN eslint-config-airbnb-base@3.0.1 requires a peer of eslint@^2.9.0 but none was installed.

```
This **notification** shows up when i was running npm install to install all the dev dependencies. And when I used   ```npm run eslint ```  this is what i recieve
 ```
npm ERR! missing script: eslint
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/01D1BFBF715C05D0/OSP/building-products-with-js/server/npm-debug.log
```` 
Any fix for this sir?

**Comment by yamalight** [comment]
@VoLuong can you tell which OS, node and npm version you use?

**Comment by VoLuong** [comment]
Thank you for having reviewed my issue.
I am on ubuntu 16.04 .
![](http://i.imgur.com/lXNTpaI.png)

**Comment by yamalight** [comment]
ah, I'm an idiot! You are trying to run npm script `eslint` which doesn't exist.
Currently, you can either run eslint as part of `npm test` script, or you can execute it manually.
To run it manually, just call `./node_modules/.bin/eslint src/`

I'll close the issue, but feel free to ask more if you have any other questions w.r.t this issue :)

**Comment by VoLuong** [comment]
Oh, by the way if there is something i could say to you as a feedback : please dont switch tabs so fast. haha. I know it's your personal speed, your personal workflow but in your tutorial sometimes you are making things so fast . Thank you for a very nice tutorial. Still watching every part.

**Comment by yamalight** [comment]
@VoLuong haha, yeah, someone has already pointed that out - will try to do it better in the next videos. Thanks for feedback! :)
