### ISSUE TITLE
Passport returns 401 by default bypassing else statement in auth login

### ISSUE THREAD

**Issue by frankhinek** [yamalight/building-products-with-js#7]
While testing I discovered that it doesn't matter what status code is returned in the else clause of [server/src/auth/login.js](https://github.com/yamalight/building-products-with-js/blob/master/server/src/auth/login.js).  The associated [server/test/login.js](https://github.com/yamalight/building-products-with-js/blob/master/server/test/login.js) test always passes because it expects a 401 and ```passport.authenticate()``` returns 401, by default, if authentication fails.

It is mentioned in the [Passport documentation](http://passportjs.org/docs#authenticate):

> By default, if authentication fails, Passport will respond with a 401 Unauthorized status, and any additional route handlers will not be invoked. If authentication succeeds, the next handler will be invoked and the req.user property will be set to the authenticated user.

Here is the relevant code:

```javascript
import passport from 'passport';

export default (app) => {
  app.post('/api/login', passport.authenticate('local'), (req, res) => {
    if (req.user) {
      res.send({user: req.user});
    } else {
      res.status(401).send({error: 'Error logging in!'});
    }
  });
};
```

For example, change line 8 to ```200``` and re-run the tests:
```javascript
res.status(200).send({error: 'Error logging in!'});
```

The [server/test/login.js](https://github.com/yamalight/building-products-with-js/blob/master/server/test/login.js) test will continue to pass because it receives the 401 status response from Passport.

From reading the documentation it seems that the [Custom Callback](http://passportjs.org/docs#custom-callback) section of the Passport.js documentation contains guidance on how to solve this if the default behavior isn't desired.  It seems like either using a custom callback (or another way to refactor) should be taken or the ```else``` clause should be removed to avoid confusion in the future.

**Comment by yamalight** [comment]
That `else` is intentional. 
It's true that passport should return 401 if auth failed, but what happens if there's an edge case when passport auth succeeded, but user is still falsy? (In theory it shouldn't happen, because passport checks for falsy users, but eh)
That's why I added this else clause - to consistently return same code even if something goes wrong in middleware.
I'll close it for now, but feel free to discuss, maybe you can convince me to remove it :)
