### ISSUE TITLE
Tests fail on windows due to usage of env variable in npm script

### ISSUE THREAD

**Issue by yamalight** [yamalight/building-products-with-js#8]
To fix - move env var setting into `test/index.js`

**Comment by EliasJorgensen** [comment]
The env variable is not the only to blame, when using the regular Windows CMD.
eslint and tap-spec in the test script: `eslint src/ && NODE_ENV=testing node test/index.js | tap-spec` also fails. Windows doesn't recognize them as globally recognized commands. 

The issue can be resolved by using the newly available Linux Subsystem (beta) for Windows 10, but here, you get an error with Reqlite - the stacktrace can be found here: http://pastebin.com/mqrGp0hP.
Although, by resolving the error with Reqlite and recommend Windows users to use the Linux Subsystem,  we will also fragment the amount of users who can run the test suite, as there might be potential viewers of the course, who hasn't upgraded to Windows 10. Now the ethical decision on whether to leave out Windows <10 users, or not, remains for you to do :smile:

**Comment by yamalight** [comment]
I'll close this for now since it works for majority of people now.
Please, do let me know if you figure out what was the issue with your installation :)
